apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/managed-by: argocd
    org: Playground

resources:
- deployment.yaml
- service.yaml
# - serviceaccount.yaml

configMapGenerator:
- name: attendance-api-base-config
  behavior: create
  literals:
  - INTERNAL_SECRET_KEY=secret
  - PLATFORM=k8s
