apiVersion: v1
kind: Service
metadata:
  name: attendance
spec:
  selector:
    name: attendance-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
  type: ClusterIP  # Change to LoadBalancer or ClusterIP based on your needs