apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ingress
  annotations:
    # nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  namespace: argocd
spec:
  rules:
  - host: argocd.playground.io
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: argocd-server
            port:
              number: 80