apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform-dev
  namespace: argocd
  creationTimestamp: null
  annotations:
    argocd-autopilot.argoproj-labs.io/default-dest-server: https://kubernetes.default.svc
    argocd.argoproj.io/sync-options: PruneLast=true
    argocd.argoproj.io/sync-wave: "-2"
spec:
  description: playground platform project
  sourceRepos:
    - 'https://github.com/devunderslash/devops-sre-platform.git'
  destinations:
    - namespace: 'apps'
      name: 'in-cluster'
    - namespace: '!argocd'
      name: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
