# The following docker-compose file is for Local testing only

services:
  backend:
    build:
      context: ../
      dockerfile: containerization/Dockerfile.backend
    image: backend
    container_name: backend
    env_file:
      - ../containerization/.env.local
    ports:
      - "5001:5001"
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DATABASE_URL: ${DATABASE_URL}
      SQLALCHEMY_DATABASE_URI: ${SQLALCHEMY_DATABASE_URI}
      SQLALCHEMY_TRACK_MODIFICATIONS: ${SQLALCHEMY_TRACK_MODIFICATIONS}
      SQLALCHEMY_ENGINE_OPTIONS: ${SQLALCHEMY_ENGINE_OPTIONS}
    depends_on:
      - db
    networks:
      - backend-network

  db:
    image: postgres:17
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge