apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: cluster-secret-store
spec:
  provider:
    vault:
      server: https://vault.default.svc:8200
      path: argocd
      version: v2
      auth:
        tokenSecretRef:
          name: vault-creds
          key: token
          namespace: external-secrets
