apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-secret
spec:
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  refreshInterval: 15s
  target:
    name: attendance
  data:
    - secretKey: SQLALCHEMY_DATABASE_URI
      remoteRef:
        key: attendance
        property: SQLALCHEMY_DATABASE_URI