# Github action to build the backend image and push it to Github Container Registry
name: Build Backend Image

on:
# trigger workflow manually
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

# build the backend image with the dockerfile located: containerization/Dockerfile.backend
    - name: Build the backend image
      run: docker build -t ghcr.io/${{ github.repository }}/backend:latest -f containerization/Dockerfile.backend .

# login to Github Container Registry
    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

# push the backend image to Github Container Registry with the following tags: latest, commit hash and semver based off the git tag
    - name: Push the backend image
      run: |
        docker push ghcr.io/${{ github.repository }}/backend:latest
        docker push ghcr.io/${{ github.repository }}/backend:${{ github.sha }}
        docker push ghcr.io/${{ github.repository }}/backend:${{ github.ref }}
