# Github action to build the backend image and push it to Github Container Registry
name: Build Backend Image


on:
# trigger workflow manually
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # TODO:
    # Set up tests for the backend
    # run Bandit, SAST, DAST, etc.
  

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # build the backend image with the dockerfile located: containerization/
    - name: Build the backend image
      run: docker build -t ghcr.io/${{ github.repository }}/backend:latest -f containerization/Dockerfile.backend_distroless .

    # login to Github Container Registry
    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    # Example of logging into AWS ECR
    # - name: Login to AWS ECR
    #   run: aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

    # TODO
    # steps for pushing to AWS ECR (optional)
    # Signing the image with Docker Content Trust (optional)
    # Security Scanning the image with Trivy (optional)

    # Fetch the tags and find the latest backend tag
    - name: Fetch tags
      run: git fetch --tags

    - name: Find latest backend tag
      id: find_tag
      run: echo "TAG=$(git describe --tags $(git rev-list --tags --max-count=1))" >> $GITHUB_ENV

    # Push the backend image to Github Container Registry with the following tags: latest, commit hash and semver based off the git tag
    - name: Tag and Push the backend image
      run: |

        docker tag ghcr.io/${{ github.repository }}/backend:latest ghcr.io/${{ github.repository }}/backend:${{ github.sha }}
        docker tag ghcr.io/${{ github.repository }}/backend:latest ghcr.io/${{ github.repository }}/backend:${{ env.TAG }}

        docker push ghcr.io/${{ github.repository }}/backend:latest
        docker push ghcr.io/${{ github.repository }}/backend:${{ github.sha }}
        docker push ghcr.io/${{ github.repository }}/backend:${{ env.TAG }}
