# Github action to build the backend image and push it to Github Container Registry
name: Test and Build Backend Image

on:
# trigger workflow manually
  workflow_dispatch:

# on:
#   push:
#     branches:
#       - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:  
    # actions/checkout@v3 is a community action that checks out your repository so your workflow can access it
    - uses: actions/checkout@v3

    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Build the backend image with the dockerfile located: containerization/
    - name: Build the backend image
      run: docker build -t ghcr.io/${{ github.repository }}/backend:latest -f containerization/Dockerfile.backend_distroless .

    # Login to Github Container Registry
    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    # Example of logging into AWS ECR (need to add AWS creds to the repository Github secrets)
    # - name: Login to AWS ECR
    #   run: aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

    # TODO
    # steps for pushing to AWS ECR (optional)
    # Security Scanning the image with Trivy (optional)

    # Fetch the tags and find the latest backend tag
    - name: Fetch tags
      run: git fetch --tags

    - name: Find latest backend tag
      id: find_tag
      run: echo "TAG=$(git describe --tags $(git rev-list --tags --max-count=1))" >> $GITHUB_ENV

    # Push the backend image to Github Container Registry with the following tags: latest, commit hash and semver based off the git tag
    - name: Tag and Push the backend image
      run: |

        docker tag ghcr.io/${{ github.repository }}/backend:latest ghcr.io/${{ github.repository }}/backend:${{ github.sha }}
        docker tag ghcr.io/${{ github.repository }}/backend:latest ghcr.io/${{ github.repository }}/backend:${{ env.TAG }}

        docker push ghcr.io/${{ github.repository }}/backend:latest
        docker push ghcr.io/${{ github.repository }}/backend:${{ github.sha }}
        docker push ghcr.io/${{ github.repository }}/backend:${{ env.TAG }}

    # Sign the image with Cosign and attestations (metadata) (optional)
    - name: Get image digest
      id: digest
      run: |
        DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' ghcr.io/${{ github.repository }}/backend:latest)
          echo "DIGEST=${DIGEST}" >> $GITHUB_ENV

    - uses: sigstore/cosign-installer@main

    - name: Write signing key to disk (only needed for `cosign sign --key`)
      run: echo "${{ secrets.COSIGN_KEY}}" > cosign.key

    - name: Sign container image
      run: |
        cosign sign --key cosign.key  --yes \
          -a "repo=${{ github.repository }}" \
          -a "workflow=${{ github.workflow }}" \
          -a "ref=${{ github.sha }}" \
          ${{ env.DIGEST }}
      env:
        COSIGN_PASSWORD: ${{secrets.COSIGN_PASSWORD}}

    # - name: Notify Slack
    #   uses: rtCamp/action-slack-notify@v2
    #   with:
    #     status: ${{ job.status }}
    #     author_name: ${{ github.actor }}
    #     author_icon: ${{ github.actor }}
    #     title: ${{ github.repository }}
    #     text: ${{ github.sha }}
    #     fields: repo, sha, event, status, workflow, job, ref
    #     slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
    #     slack_channel: ${{ secrets.SLACK_CHANNEL }}
    #     slack_username: ${{ secrets.SLACK_USERNAME }}

